[features]
seeds = false
[programs.devnet]
myepicsolanaproject = "69FFL93bP9vpVpCvRMxb5LrE1qQZCUbvcVyGjDhdTdfM"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/yihfoo/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
